version: "3.8"
services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
       DATABASE_HOST : localhost
       POSTGRES_PASSWORD : ptmpaaa
       POSTGRES_DB : Anylist
    container_name: anylistDB
    
